import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/user_model.dart';
import '../models/meal_model.dart';
import '../models/nutrition_model.dart';
import '../models/weight_entry_model.dart';
import '../models/journal_entry_model.dart';
import '../models/achievement_model.dart';

class DataService {
  static const String userBoxName = 'user';
  static const String mealsBoxName = 'meals';
  static const String weightsBoxName = 'weights';
  static const String journalsBoxName = 'journals';
  static const String achievementsBoxName = 'achievements';
  static const String settingsBoxName = 'settings';

  // Initialize Hive
  static Future<void> initialize() async {
    await Hive.initFlutter();

    // Register adapters (these will be generated by build_runner)
    // Hive.registerAdapter(UserModelAdapter());
    // Hive.registerAdapter(MealModelAdapter());
    // Hive.registerAdapter(NutritionModelAdapter());
    // Hive.registerAdapter(WeightEntryModelAdapter());
    // Hive.registerAdapter(JournalEntryModelAdapter());
    // Hive.registerAdapter(AchievementModelAdapter());

    // Open boxes
    await Hive.openBox<UserModel>(userBoxName);
    await Hive.openBox<MealModel>(mealsBoxName);
    await Hive.openBox<WeightEntryModel>(weightsBoxName);
    await Hive.openBox<JournalEntryModel>(journalsBoxName);
    await Hive.openBox<AchievementModel>(achievementsBoxName);
    await Hive.openBox(settingsBoxName);
  }

  // User operations
  Future<void> saveUser(UserModel user) async {
    final box = Hive.box<UserModel>(userBoxName);
    await box.put('current_user', user);
  }

  UserModel? getUser() {
    final box = Hive.box<UserModel>(userBoxName);
    return box.get('current_user');
  }

  Future<void> updateUserStreak(int streak) async {
    final user = getUser();
    if (user != null) {
      user.currentStreak = streak;
      if (streak > user.longestStreak) {
        user.longestStreak = streak;
      }
      await saveUser(user);
    }
  }

  Future<void> updateUserWeight(double weight) async {
    final user = getUser();
    if (user != null) {
      user.currentWeight = weight;
      await saveUser(user);
    }
  }

  Future<void> addUserPoints(int points) async {
    final user = getUser();
    if (user != null) {
      user.totalPoints += points;
      await saveUser(user);
    }
  }

  // Meal operations
  Future<void> saveMeal(MealModel meal) async {
    final box = Hive.box<MealModel>(mealsBoxName);
    await box.put(meal.id, meal);
  }

  Future<void> deleteMeal(String mealId) async {
    final box = Hive.box<MealModel>(mealsBoxName);
    await box.delete(mealId);
  }

  List<MealModel> getAllMeals() {
    final box = Hive.box<MealModel>(mealsBoxName);
    return box.values.toList();
  }

  List<MealModel> getMealsByDate(DateTime date) {
    final box = Hive.box<MealModel>(mealsBoxName);
    return box.values.where((meal) {
      return meal.timestamp.year == date.year &&
          meal.timestamp.month == date.month &&
          meal.timestamp.day == date.day;
    }).toList();
  }

  List<MealModel> getMealsByDateRange(DateTime start, DateTime end) {
    final box = Hive.box<MealModel>(mealsBoxName);
    return box.values.where((meal) {
      return meal.timestamp.isAfter(start) && meal.timestamp.isBefore(end);
    }).toList();
  }

  // Get today's nutrition total
  NutritionModel getTodayNutrition() {
    final todayMeals = getMealsByDate(DateTime.now());
    NutritionModel total = NutritionModel();

    for (var meal in todayMeals) {
      total = total + meal.nutrition;
    }

    return total;
  }

  // Weight operations
  Future<void> saveWeightEntry(WeightEntryModel entry) async {
    final box = Hive.box<WeightEntryModel>(weightsBoxName);
    await box.put(entry.id, entry);

    // Update user's current weight
    await updateUserWeight(entry.weight);
  }

  Future<void> deleteWeightEntry(String entryId) async {
    final box = Hive.box<WeightEntryModel>(weightsBoxName);
    await box.delete(entryId);
  }

  List<WeightEntryModel> getAllWeightEntries() {
    final box = Hive.box<WeightEntryModel>(weightsBoxName);
    final entries = box.values.toList();
    entries.sort((a, b) => b.date.compareTo(a.date));
    return entries;
  }

  WeightEntryModel? getLatestWeightEntry() {
    final entries = getAllWeightEntries();
    return entries.isEmpty ? null : entries.first;
  }

  // Journal operations
  Future<void> saveJournalEntry(JournalEntryModel entry) async {
    final box = Hive.box<JournalEntryModel>(journalsBoxName);
    await box.put(entry.id, entry);
  }

  Future<void> deleteJournalEntry(String entryId) async {
    final box = Hive.box<JournalEntryModel>(journalsBoxName);
    await box.delete(entryId);
  }

  List<JournalEntryModel> getAllJournalEntries() {
    final box = Hive.box<JournalEntryModel>(journalsBoxName);
    final entries = box.values.toList();
    entries.sort((a, b) => b.timestamp.compareTo(a.timestamp));
    return entries;
  }

  List<JournalEntryModel> getJournalEntriesByDate(DateTime date) {
    final box = Hive.box<JournalEntryModel>(journalsBoxName);
    return box.values.where((entry) {
      return entry.timestamp.year == date.year &&
          entry.timestamp.month == date.month &&
          entry.timestamp.day == date.day;
    }).toList();
  }

  // Achievement operations
  Future<void> initializeAchievements() async {
    final box = Hive.box<AchievementModel>(achievementsBoxName);

    // Only initialize if empty
    if (box.isEmpty) {
      final defaultAchievements = Achievements.getDefaultAchievements();
      for (var achievement in defaultAchievements) {
        await box.put(achievement.id, achievement);
      }
    }
  }

  Future<void> saveAchievement(AchievementModel achievement) async {
    final box = Hive.box<AchievementModel>(achievementsBoxName);
    await box.put(achievement.id, achievement);
  }

  List<AchievementModel> getAllAchievements() {
    final box = Hive.box<AchievementModel>(achievementsBoxName);
    return box.values.toList();
  }

  List<AchievementModel> getUnlockedAchievements() {
    return getAllAchievements().where((a) => a.isUnlocked).toList();
  }

  Future<void> unlockAchievement(String achievementId, int points) async {
    final box = Hive.box<AchievementModel>(achievementsBoxName);
    final achievement = box.get(achievementId);

    if (achievement != null && !achievement.isUnlocked) {
      achievement.isUnlocked = true;
      achievement.unlockedAt = DateTime.now();
      await box.put(achievementId, achievement);

      // Add points to user
      await addUserPoints(points);
    }
  }

  Future<void> updateAchievementProgress(String achievementId, int progress) async {
    final box = Hive.box<AchievementModel>(achievementsBoxName);
    final achievement = box.get(achievementId);

    if (achievement != null) {
      achievement.currentProgress = progress;

      // Auto-unlock if requirement met
      if (progress >= achievement.requiredProgress && !achievement.isUnlocked) {
        await unlockAchievement(achievementId, achievement.points);
      } else {
        await box.put(achievementId, achievement);
      }
    }
  }

  // Streak calculation
  int calculateCurrentStreak() {
    final user = getUser();
    if (user == null) return 0;

    final loginDates = user.loginDates;
    if (loginDates.isEmpty) return 0;

    loginDates.sort((a, b) => b.compareTo(a));

    final today = DateTime.now();
    final todayDate = DateTime(today.year, today.month, today.day);

    int streak = 0;
    DateTime checkDate = todayDate;

    for (var loginDate in loginDates) {
      final normalizedLogin = DateTime(loginDate.year, loginDate.month, loginDate.day);

      if (normalizedLogin == checkDate) {
        streak++;
        checkDate = checkDate.subtract(const Duration(days: 1));
      } else if (normalizedLogin.isBefore(checkDate)) {
        // Gap found, streak broken
        break;
      }
    }

    return streak;
  }

  Future<void> recordDailyLogin() async {
    final user = getUser();
    if (user == null) return;

    final today = DateTime.now();
    final todayDate = DateTime(today.year, today.month, today.day);

    // Check if already logged today
    final alreadyLogged = user.loginDates.any((date) {
      final normalizedDate = DateTime(date.year, date.month, date.day);
      return normalizedDate == todayDate;
    });

    if (!alreadyLogged) {
      user.loginDates.add(today);

      // Update streak
      final newStreak = calculateCurrentStreak();
      user.currentStreak = newStreak;
      if (newStreak > user.longestStreak) {
        user.longestStreak = newStreak;
      }

      await saveUser(user);

      // Check streak achievements
      await _checkStreakAchievements(newStreak);
    }
  }

  Future<void> _checkStreakAchievements(int streak) async {
    final streakMilestones = [3, 7, 30, 100];

    for (var milestone in streakMilestones) {
      if (streak >= milestone) {
        await updateAchievementProgress('streak_$milestone', streak);
      }
    }
  }

  // Settings
  Future<void> saveSetting(String key, dynamic value) async {
    final box = Hive.box(settingsBoxName);
    await box.put(key, value);
  }

  dynamic getSetting(String key, {dynamic defaultValue}) {
    final box = Hive.box(settingsBoxName);
    return box.get(key, defaultValue: defaultValue);
  }

  // Clear all data (for logout/reset)
  Future<void> clearAllData() async {
    await Hive.box<UserModel>(userBoxName).clear();
    await Hive.box<MealModel>(mealsBoxName).clear();
    await Hive.box<WeightEntryModel>(weightsBoxName).clear();
    await Hive.box<JournalEntryModel>(journalsBoxName).clear();
    await Hive.box<AchievementModel>(achievementsBoxName).clear();
    await Hive.box(settingsBoxName).clear();
  }
}
